# Usar uma imagem base do Python
FROM python:3.11

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar os arquivos do projeto para o container
COPY . /app

# Instalar dependências


RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta da aplicação
EXPOSE 8000

# Comando para rodar o servidor Django com Gunicorn
CMD ["gunicorn", "meuprojeto.wsgi:application", "--bind", "0.0.0.0:8000"]